### ISSUE TITLE
Delete chat option

### ISSUE THREAD

**Issue by tonypr** [Messengr/Messengr#10]
Introduce option to delete chats

How to implement:
UI:
- Add delete button on chat page

App.py:
- Add route for chat_delete (if successful, redirect to home page. else, redirect back to chat page)

Models/chat.py:
- Add function to handle DB deletion of chat

**Comment by mpertierra** [comment]
I think it might make more sense to have the delete button on the home page

**Comment by tonypr** [comment]
Sounds good, I agree.

**Comment by tonypr** [comment]
Pull request #15 reverted. 

Database issues with postgres caused server errors. Fixes will be in progress.

**Comment by tonypr** [comment]
Implemented by pull request #18.
