### ISSUE TITLE
Search for users on home page

### ISSUE THREAD

**Issue by tonypr** [Messengr/Messengr#11]
We should allow users to search for other users when creating a chat. (i.e. auto complete for users when typing)

How to implement:
(there are thousands of auto complete tutorials. One with jQuery is: https://jqueryui.com/autocomplete/)

UI:
- Add suggestion list when typing in the #receiver text box. (can be done with jQuery or other libraries)

App.py:
- Add POST route that returns list of users which would match the current set of characters. (i.e. input "ton" should return user "tonypr")

user.py:
- Should do a db search to handle auto complete on string input for usernames

**Comment by mpertierra** [comment]
Implemented by @dagarcia7 in #22
